services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=platzi-store
      - POSTGRES_USER=root
      - POSTGRES_DB=123456
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data